# Generated by Django 3.1.6 on 2021-02-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_productos_observaciones_codigo_interno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompradetalle',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='ordencompradetalle',
            name='unidad_medida',
        ),
    ]
