# Generated by Django 3.1.6 on 2021-02-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_auto_20210218_1035'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordencompradetalle',
            table='orden_compra_detalle',
        ),
    ]
