# Generated by Django 3.1.2 on 2021-02-18 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20210216_0049'),
        ('pagos', '0005_auto_20210218_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='persona.persona'),
            preserve_default=False,
        ),
    ]
