# Generated by Django 3.1.2 on 2021-02-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_auto_20210218_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='monto_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total_descuento_beneficios',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
