# Generated by Django 3.1.6 on 2021-02-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_auto_20210218_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagowebpay',
            old_name='card_expiration_date',
            new_name='payment_type_code',
        ),
        migrations.RenameField(
            model_name='pagowebpay',
            old_name='commerce_code',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='pagowebpay',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='pagowebpay',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='pagowebpay',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='pagowebpay',
            name='shares_number',
        ),
        migrations.RemoveField(
            model_name='pagowebpay',
            name='tbk_id_sesion',
        ),
        migrations.RemoveField(
            model_name='pagowebpay',
            name='tbk_orden_compra',
        ),
        migrations.RemoveField(
            model_name='pagowebpay',
            name='tbk_token',
        ),
        migrations.AddField(
            model_name='pagowebpay',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pagowebpay',
            name='installments_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pagowebpay',
            name='installments_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='accounting_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='card_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='response_code',
            field=models.IntegerField(null=True),
        ),
    ]
