# Generated by Django 3.1.6 on 2021-02-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_auto_20210223_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagowebpay',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
