# Generated by Django 3.1.6 on 2021-02-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_auto_20210226_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='comentario',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='folio_dte',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='id_sesion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='ip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='pago_app',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='accounting_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='card_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
