# Generated by Django 3.1.2 on 2021-03-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_auto_20210226_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='comentario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='folio_dte',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='id_sesion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='ip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='pago_app',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='token_webpay',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
