# Generated by Django 3.1.2 on 2021-03-31 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0012_auto_20210310_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'permissions': [('recibir_pagos', 'Puede marcar ordenes de compra como pagadas')]},
        ),
    ]
