# Generated by Django 3.1.2 on 2021-04-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_auto_20210331_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='folio_dte',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
