# Generated by Django 3.1.2 on 2021-06-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0014_auto_20210414_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='folio_dte',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
