# Generated by Django 4.0 on 2022-01-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0015_auto_20210608_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado_pago',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'pagada'), (2, 'rechazada'), (3, 'anulada'), (4, 'inválida')]),
        ),
    ]
