# Generated by Django 4.0.3 on 2022-09-08 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0016_alter_ordencompra_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasproductos',
            name='estado',
            field=models.BooleanField(help_text='no utilizado en matrícula'),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='estado',
            field=models.BooleanField(help_text='no utilizado en matrícula'),
        ),
        migrations.AlterField(
            model_name='modalidadpago',
            name='estado',
            field=models.BooleanField(help_text='no utilizado en matrícula'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.BooleanField(help_text='define si la orden compra terminó o no, independiente del resultado'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='monto_total',
            field=models.IntegerField(default=0, help_text='monto inicial sin contar beneficios'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='pago_app',
            field=models.CharField(blank=True, help_text='no utilizado en matrícula', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='token_webpay',
            field=models.CharField(blank=True, help_text='utilizado para integración con webpay', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompradetalle',
            name='descuento',
            field=models.IntegerField(help_text='no utilizado en matrícula', null=True),
        ),
        migrations.AlterField(
            model_name='ordencompradetalle',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.ordencompra'),
        ),
        migrations.AlterField(
            model_name='pagocheque',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.ordencompra'),
        ),
        migrations.AlterField(
            model_name='pagodepositobancario',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.ordencompra'),
        ),
        migrations.AlterField(
            model_name='pagoefectivo',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.ordencompra'),
        ),
        migrations.AlterField(
            model_name='pagoredcompra',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.ordencompra'),
        ),
        migrations.AlterField(
            model_name='pagotransferenciabancaria',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.ordencompra'),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='accounting_date',
            field=models.CharField(help_text='fecha autorización (MMDD)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='authorization_code',
            field=models.CharField(help_text='código de autorización', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='balance',
            field=models.IntegerField(help_text='no utilizado en matrícula', null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='buy_order',
            field=models.CharField(help_text='se utiliza el id de la orden de compra', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='card_number',
            field=models.CharField(help_text='útlimos 4 dígitos', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='installments_amount',
            field=models.IntegerField(help_text='valor de cuotas', null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='installments_number',
            field=models.IntegerField(help_text='número de cuotas', null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.ordencompra'),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='payment_type_code',
            field=models.CharField(help_text='tipo de venta, explicados en función completar', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='response_code',
            field=models.IntegerField(help_text='0 si es aprobada, negativo en caso contrario', null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='session_id',
            field=models.CharField(help_text='no se utilizan sesiones en SGA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='status',
            field=models.CharField(help_text='estado de la transacción', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='token',
            field=models.CharField(help_text='generado por webpay para realizar integración', max_length=200),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='transaction_date',
            field=models.CharField(help_text='fecha-hora autorización (yyyy-mm-ddTHH: mm: ss.xxxZ)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagowebpay',
            name='vci',
            field=models.CharField(help_text='resultado de autenticación', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigo_interno',
            field=models.IntegerField(help_text='no utilizado en matrícula', null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion_corta',
            field=models.CharField(help_text='no utilizado en matrícula', max_length=200),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion_larga',
            field=models.CharField(help_text='no utilizado en matrícula', max_length=400),
        ),
        migrations.AlterField(
            model_name='productos',
            name='destacado',
            field=models.BooleanField(help_text='no utilizado en matrícula', null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.BooleanField(help_text='no utilizado en matrícula'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='marca',
            field=models.CharField(help_text='no utilizado en matrícula', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='numero_serie',
            field=models.CharField(help_text='no utilizado en matrícula', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='numero_vistas',
            field=models.IntegerField(help_text='no utilizado en matrícula', null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='observaciones_codigo_interno',
            field=models.CharField(help_text='no utilizado en matrícula', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(help_text='no utilizado en matrícula'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='unidad_medida',
            field=models.CharField(help_text='no utilizado en matrícula', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='valor_antes',
            field=models.IntegerField(help_text='no utilizado en matrícula', null=True),
        ),
        migrations.AlterField(
            model_name='subcategoriasproductos',
            name='estado',
            field=models.BooleanField(help_text='no utilizado en matrícula'),
        ),
    ]
