# Generated by Django 3.1.2 on 2020-12-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='ConjuntoRamos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'conjunto_ramos',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('creditos', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.departamento')),
                ('equivalencias', models.ManyToManyField(related_name='_ramo_equivalencias_+', to='academica.Ramo')),
            ],
            options={
                'db_table': 'ramo',
                'ordering': ['departamento', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.ramo')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academica.ramo')),
            ],
            options={
                'db_table': 'requisito',
            },
        ),
        migrations.AddField(
            model_name='ramo',
            name='requisitos',
            field=models.ManyToManyField(related_name='_ramo_requisitos_+', through='academica.Requisito', to='academica.Ramo'),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.carrera')),
            ],
            options={
                'verbose_name_plural': 'Planes',
                'db_table': 'plan',
                'unique_together': {('carrera', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MallaObligatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.PositiveSmallIntegerField()),
                ('tipo_formacion', models.PositiveSmallIntegerField(choices=[(0, 'formación básica'), (1, 'formación transversal'), (2, 'formación especializada')])),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='malla_obligatoria', to='academica.plan')),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='malla_obligatoria', to='academica.ramo')),
            ],
            options={
                'db_table': 'malla_obligatoria',
                'default_related_name': 'malla_obligatoria',
            },
        ),
        migrations.CreateModel(
            name='MallaElectiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.PositiveSmallIntegerField()),
                ('tipo_formacion', models.PositiveSmallIntegerField(choices=[(0, 'formación básica'), (1, 'formación transversal'), (2, 'formación especializada')])),
                ('nombre', models.CharField(max_length=200)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('conjunto_ramos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='malla_electiva', to='academica.conjuntoramos')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='malla_electiva', to='academica.plan')),
            ],
            options={
                'db_table': 'malla_electiva',
                'default_related_name': 'malla_electiva',
            },
        ),
        migrations.AddField(
            model_name='conjuntoramos',
            name='ramos',
            field=models.ManyToManyField(blank=True, to='academica.Ramo'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.departamento'),
        ),
    ]
