# Generated by Django 3.1.2 on 2021-02-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='tipo',
        ),
        migrations.AddField(
            model_name='plan',
            name='codigo_demre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
