# Generated by Django 3.1.2 on 2021-02-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0002_auto_20210216_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='codigo_demre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
