# Generated by Django 3.1.2 on 2021-05-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0003_auto_20210223_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='tipo_carrera',
            field=models.PositiveSmallIntegerField(choices=[(0, 'carrera'), (1, 'diplomado'), (2, 'post título'), (3, 'magister'), (4, 'doctorado')], default=0),
            preserve_default=False,
        ),
    ]
