# Generated by Django 3.1.2 on 2021-05-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0004_carrera_tipo_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='link_decreto',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
