# Generated by Django 3.2.5 on 2021-08-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0006_auto_20210608_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='tipo_carrera',
            field=models.PositiveSmallIntegerField(choices=[(0, 'carrera'), (1, 'diplomado')]),
        ),
    ]
