# Generated by Django 3.2.5 on 2021-08-16 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0007_alter_carrera_tipo_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='id_SAI',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_ucampus',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ramo',
            name='id_SAI',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ramo',
            name='id_ucampus',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='id_SAI',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='id_ucampus',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id_SAI',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id_ucampus',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ramo',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academica.departamento'),
        ),
        migrations.AlterUniqueTogether(
            name='mallaobligatoria',
            unique_together={('plan', 'ramo')},
        ),
    ]
