# Generated by Django 3.2.5 on 2021-10-15 20:36

from django.db import migrations


def actualizar_nulo_a_vacio(apps, schema_editor):
    Plan = apps.get_model('academica', 'Plan')
    Plan.objects.filter(id_ucampus__isnull=True).update(id_ucampus=0)
    return


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0008_auto_20210816_1729'),
    ]

    operations = [
        migrations.RunPython(actualizar_nulo_a_vacio, migrations.RunPython.noop)
    ]
