# Generated by Django 3.2.5 on 2021-10-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0009_auto_20211015_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='codigo_ucampus',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id_ucampus',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
