# Generated by Django 4.0 on 2021-12-15 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0010_auto_20211025_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mallaelectiva',
            name='conjunto_ramos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.conjuntoramos'),
        ),
        migrations.AlterField(
            model_name='mallaelectiva',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.plan'),
        ),
        migrations.AlterField(
            model_name='mallaobligatoria',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.plan'),
        ),
        migrations.AlterField(
            model_name='mallaobligatoria',
            name='ramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.ramo'),
        ),
        migrations.AlterField(
            model_name='ramo',
            name='equivalencias',
            field=models.ManyToManyField(to='academica.Ramo'),
        ),
        migrations.AlterField(
            model_name='ramo',
            name='requisitos',
            field=models.ManyToManyField(related_name='+', through='academica.Requisito', to='academica.Ramo'),
        ),
    ]
