# Generated by Django 4.0 on 2022-06-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0011_alter_mallaelectiva_conjunto_ramos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='tipo_carrera',
            field=models.PositiveSmallIntegerField(choices=[(0, 'carrera'), (1, 'diplomado'), (2, 'curso de especializacion')]),
        ),
    ]
