# Generated by Django 4.0.6 on 2022-11-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0013_alter_mallaelectiva_semestre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramo',
            name='requisito_creditaje',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ramo',
            name='requisito_nivel',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
