# Generated by Django 4.0 on 2021-12-15 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0013_historialestadoestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.CharField(max_length=12)),
                ('valido', models.BooleanField(default=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('tipo_certificado', models.PositiveSmallIntegerField(choices=[(0, 'Estudiante Regular'), (1, 'Otros')], default=0)),
                ('archivo', models.FilePathField(null=True, path='C:\\Users\\crist\\Documents\\UdeAysen\\Proyecto\\uaysen-online-backend\\media\\certificados')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.estudiante')),
            ],
            options={
                'db_table': 'certificado',
            },
        ),
    ]
