# Generated by Django 4.0 on 2021-12-29 15:03

import certificados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='archivo',
            field=models.FilePathField(null=True, path=certificados.models.dir_certificados),
        ),
    ]
