# Generated by Django 4.0 on 2022-01-11 19:28

import certificados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_alter_certificado_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='llave',
            field=models.CharField(default=certificados.models.generar_llave, max_length=12),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='tipo_certificado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'estudiante regular'), (1, 'matrícula'), (2, 'otros')], default=0),
        ),
    ]
