# Generated by Django 4.0.3 on 2022-04-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_alter_certificado_llave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='tipo_certificado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'estudiante regular'), (1, 'matrícula'), (2, 'notas'), (3, 'especial')], default=0),
        ),
    ]
