# Generated by Django 4.0.3 on 2022-05-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0017_auto_20220419_1505'),
        ('certificados', '0004_alter_certificado_tipo_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'aceptada'), (2, 'rechazada'), (3, 'expirada')], default=0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.estudiante')),
            ],
            options={
                'db_table': 'solicitud_certificado',
            },
        ),
    ]
