# Generated by Django 4.0.3 on 2022-05-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0005_solicitudcertificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcertificado',
            name='certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificados.certificado'),
        ),
        migrations.AddField(
            model_name='solicitudcertificado',
            name='contenido_revisor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcertificado',
            name='justificacion',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudcertificado',
            name='titulo_revisor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='tipo_certificado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'estudiante regular'), (1, 'matrícula'), (2, 'notas'), (3, 'personalizado')], default=0),
        ),
        migrations.AlterField(
            model_name='solicitudcertificado',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'aceptada'), (2, 'rechazada')], default=0),
        ),
    ]
