# Generated by Django 4.0 on 2022-07-04 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0006_solicitudcertificado_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcertificado',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
