# Generated by Django 3.1.2 on 2021-02-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0002_auto_20201211_1534'),
        ('persona', '0008_auto_20210205_1742'),
        ('academica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioAdmisionEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'criterio_admision_especial',
            },
        ),
        migrations.CreateModel(
            name='EtapaMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('numero', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'etapa_matricula',
            },
        ),
        migrations.CreateModel(
            name='PostulanteDefinitivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('numero_demre', models.CharField(max_length=50)),
                ('resultado_postulacion', models.PositiveSmallIntegerField(choices=[(0, 'seleccionado'), (1, 'lista de espera')])),
                ('posicion_lista_espera', models.PositiveSmallIntegerField()),
                ('preseleccionado_gratuidad', models.BooleanField()),
                ('habilitado', models.BooleanField()),
                ('acepta_vacante', models.BooleanField()),
                ('estudiante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.estudiante')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.plan')),
            ],
            options={
                'db_table': 'postulante_definitivo',
            },
        ),
        migrations.CreateModel(
            name='ProcesoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('ano', models.PositiveSmallIntegerField()),
                ('fecha_vigencia', models.DateField()),
                ('activo', models.BooleanField()),
                ('periodo_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.periodo')),
            ],
            options={
                'db_table': 'proceso_matricula',
            },
        ),
        migrations.CreateModel(
            name='ViaIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'via_ingreso',
            },
        ),
        migrations.CreateModel(
            name='ValorMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('valor', models.PositiveIntegerField()),
                ('decreto', models.CharField(max_length=200)),
                ('decreto_ano', models.PositiveSmallIntegerField()),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
            ],
            options={
                'db_table': 'valor_matricula',
            },
        ),
        migrations.CreateModel(
            name='ValorArancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('valor', models.PositiveIntegerField()),
                ('decreto', models.CharField(max_length=200)),
                ('decreto_ano', models.PositiveSmallIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.plan')),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
            ],
            options={
                'db_table': 'valor_arancel',
            },
        ),
        migrations.CreateModel(
            name='TNEEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'pagado')])),
                ('orden_compra', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.estudiante')),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
            ],
            options={
                'db_table': 'tne_estudiante',
            },
        ),
        migrations.CreateModel(
            name='SubcriterioAdmisionEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.criterioadmisionespecial')),
            ],
            options={
                'db_table': 'subcriterio_admision_especial',
            },
        ),
        migrations.CreateModel(
            name='RegistroPostulanteHabilitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado_anterior', models.BooleanField()),
                ('fecha_cambio', models.DateField()),
                ('autor_cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
                ('postulante_definitivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.postulantedefinitivo')),
            ],
            options={
                'db_table': 'registro_postulante_habilitado',
            },
        ),
        migrations.CreateModel(
            name='PostulanteRegular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('resultado_postulacion', models.PositiveSmallIntegerField(choices=[(0, 'seleccionado'), (1, 'lista de espera')])),
                ('posicion_lista_espera', models.PositiveSmallIntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.plan')),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
                ('via_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.viaingreso')),
            ],
            options={
                'db_table': 'postulante_regular',
            },
        ),
        migrations.CreateModel(
            name='PostulanteEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('puntaje', models.PositiveSmallIntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.plan')),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
                ('subcriterio_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.subcriterioadmisionespecial')),
            ],
            options={
                'db_table': 'postulante_especial',
            },
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='proceso_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula'),
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='via_ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.viaingreso'),
        ),
        migrations.CreateModel(
            name='PeriodoProcesoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('publico', models.PositiveSmallIntegerField(choices=[(0, 'primer año'), (1, 'curso superior')])),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
            ],
            options={
                'db_table': 'periodo_proceso_matricula',
            },
        ),
        migrations.CreateModel(
            name='OfertaAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('cupos_regulares', models.PositiveSmallIntegerField()),
                ('cupos_BEA', models.PositiveSmallIntegerField()),
                ('cupos_PACE', models.PositiveSmallIntegerField()),
                ('cupos_especiales', models.PositiveSmallIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.plan')),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
            ],
            options={
                'db_table': 'oferta_academica',
            },
        ),
        migrations.CreateModel(
            name='MatriculaEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'pagado')])),
                ('orden_compra', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.estudiante')),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
            ],
            options={
                'db_table': 'matricula_estudiante',
            },
        ),
        migrations.CreateModel(
            name='InhabilitantesMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tiene_deuda_finanzas', models.BooleanField()),
                ('tiene_deuda_biblioteca', models.BooleanField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.estudiante')),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
            ],
            options={
                'db_table': 'inhabilitantes_matricula',
            },
        ),
        migrations.CreateModel(
            name='EtapaPostulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('etapa_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.etapamatricula')),
                ('postulante_definitivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.postulantedefinitivo')),
            ],
            options={
                'db_table': 'etapa_postulante',
            },
        ),
        migrations.CreateModel(
            name='ArancelEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('monto', models.IntegerField()),
                ('tiene_beneficios', models.BooleanField()),
                ('beneficios_monto_total', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('pago_cuotas', models.BooleanField()),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'pago en cuotas pendiente'), (2, 'pagado')])),
                ('orden_compra', models.IntegerField()),
                ('pagare_estudiante', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.estudiante')),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
                ('valor_arancel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.valorarancel')),
            ],
            options={
                'db_table': 'arancel_estudiante',
            },
        ),
    ]
