# Generated by Django 3.1.2 on 2021-02-11 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
        ('persona', '0002_auto_20210205_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='GratuidadEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tiene_gratuidad', models.BooleanField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.estudiante')),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
            ],
            options={
                'db_table': 'gratuidad_estudiante',
            },
        ),
        migrations.AddField(
            model_name='tneestudiante',
            name='paga_TNE',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arancelestudiante',
            name='beneficios_monto_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arancelestudiante',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arancelestudiante',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'pago en cuotas pendiente'), (2, 'pagado')], default=0),
        ),
        migrations.AlterField(
            model_name='arancelestudiante',
            name='orden_compra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arancelestudiante',
            name='pagare_estudiante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arancelestudiante',
            name='pago_cuotas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arancelestudiante',
            name='tiene_beneficios',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matriculaestudiante',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'pagado')], default=0),
        ),
        migrations.AlterField(
            model_name='matriculaestudiante',
            name='orden_compra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tneestudiante',
            name='estado',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'pendiente'), (1, 'pagado')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tneestudiante',
            name='orden_compra',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
