# Generated by Django 3.1.2 on 2021-02-18 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20210216_0049'),
        ('academica', '0002_auto_20210216_1331'),
        ('matricula', '0003_auto_20210216_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapamatricula',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='procesomatricula',
            name='ano',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='valormatricula',
            name='proceso_matricula',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula'),
        ),
        migrations.AlterUniqueTogether(
            name='arancelestudiante',
            unique_together={('proceso_matricula', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='etapapostulante',
            unique_together={('postulante_definitivo', 'etapa_matricula')},
        ),
        migrations.AlterUniqueTogether(
            name='gratuidadestudiante',
            unique_together={('proceso_matricula', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='inhabilitantesmatricula',
            unique_together={('proceso_matricula', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='matriculaestudiante',
            unique_together={('proceso_matricula', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='ofertaacademica',
            unique_together={('proceso_matricula', 'plan')},
        ),
        migrations.AlterUniqueTogether(
            name='postulanteespecial',
            unique_together={('persona', 'proceso_matricula', 'plan')},
        ),
        migrations.AlterUniqueTogether(
            name='postulanteregular',
            unique_together={('persona', 'proceso_matricula', 'plan')},
        ),
        migrations.AlterUniqueTogether(
            name='tneestudiante',
            unique_together={('proceso_matricula', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='valorarancel',
            unique_together={('proceso_matricula', 'plan')},
        ),
    ]
