# Generated by Django 3.1.2 on 2021-02-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_auto_20210218_1102'),
        ('matricula', '0004_auto_20210218_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arancelestudiante',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagos.ordencompra'),
        ),
        migrations.AlterField(
            model_name='matriculaestudiante',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagos.ordencompra'),
        ),
        migrations.AlterField(
            model_name='tneestudiante',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagos.ordencompra'),
        ),
    ]
