# Generated by Django 3.1.2 on 2021-02-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_auto_20210218_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arancelestudiante',
            name='beneficios_monto_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arancelestudiante',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arancelestudiante',
            name='pago_cuotas',
            field=models.BooleanField(default=False),
        ),
    ]
