# Generated by Django 3.1.2 on 2021-02-19 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20210216_0049'),
        ('matricula', '0006_auto_20210218_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.estudiante')),
            ],
            options={
                'db_table': 'etapa_estudiante',
            },
        ),
        migrations.AlterField(
            model_name='etapamatricula',
            name='numero',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='EtapaPostulante',
        ),
        migrations.AddField(
            model_name='etapaestudiante',
            name='etapa_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.etapamatricula'),
        ),
        migrations.AddField(
            model_name='etapaestudiante',
            name='proceso_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula'),
        ),
        migrations.AlterUniqueTogether(
            name='etapaestudiante',
            unique_together={('estudiante', 'etapa_matricula', 'proceso_matricula')},
        ),
    ]
