# Generated by Django 3.1.2 on 2021-02-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0002_auto_20210216_1331'),
        ('persona', '0003_auto_20210216_0049'),
        ('matricula', '0007_auto_20210219_1709'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postulantedefinitivo',
            unique_together={('persona', 'proceso_matricula', 'plan', 'via_ingreso')},
        ),
        migrations.AlterUniqueTogether(
            name='postulanteregular',
            unique_together={('persona', 'proceso_matricula', 'plan', 'via_ingreso')},
        ),
    ]
