# Generated by Django 3.1.2 on 2021-03-01 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20210228_0215'),
        ('matricula', '0010_auto_20210226_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteRespondeEncuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('responde_encuesta', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.estudiante')),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
            ],
            options={
                'db_table': 'estudiante_responde_encuesta',
                'unique_together': {('proceso_matricula', 'estudiante')},
            },
        ),
    ]
