# Generated by Django 3.1.2 on 2021-03-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0011_estudianterespondeencuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabilitantesmatricula',
            name='comentario_biblioteca',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inhabilitantesmatricula',
            name='comentario_finanzas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='matriculaestudiante',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'válida'), (2, 'anulada por cambio de carrera'), (3, 'anulada por retracto'), (4, 'anulada por otro motivo')], default=0),
        ),
    ]
