# Generated by Django 3.1.2 on 2021-03-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0012_auto_20210315_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabilitantesmatricula',
            name='tiene_deuda_biblioteca',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inhabilitantesmatricula',
            name='tiene_deuda_finanzas',
            field=models.BooleanField(default=False),
        ),
    ]
