# Generated by Django 3.1.2 on 2021-03-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0013_auto_20210316_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabilitantesmatricula',
            name='comentario_biblioteca',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='inhabilitantesmatricula',
            name='comentario_finanzas',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
