# Generated by Django 3.1.2 on 2021-03-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0014_auto_20210316_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='PACE',
            field=models.BooleanField(default=False),
        ),
    ]
