# Generated by Django 3.1.2 on 2021-04-14 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0003_auto_20210223_2204'),
        ('persona', '0009_auto_20210316_1238'),
        ('matricula', '0015_postulantedefinitivo_pace'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulantePostgrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(max_length=50)),
                ('acepta_vacante', models.BooleanField(default=False)),
                ('tipo_descuento', models.PositiveSmallIntegerField(choices=[(0, 'monto fijo'), (1, 'porcentual')], default=0)),
                ('monto_descuento', models.PositiveIntegerField()),
                ('estudiante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.estudiante')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.plan')),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
            ],
            options={
                'db_table': 'postulante_postgrado',
                'unique_together': {('persona', 'proceso_matricula', 'plan')},
            },
        ),
    ]
