# Generated by Django 3.1.2 on 2021-04-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0016_postulantepostgrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantepostgrado',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postulantepostgrado',
            name='posicion_lista',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulantepostgrado',
            name='resultado_postulacion',
            field=models.PositiveSmallIntegerField(choices=[(0, 'seleccionado'), (1, 'lista de espera')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periodoprocesomatricula',
            name='publico',
            field=models.PositiveSmallIntegerField(choices=[(0, 'primer año'), (1, 'curso superior'), (2, 'formación continua')]),
        ),
        migrations.AlterField(
            model_name='postulantepostgrado',
            name='monto_descuento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulantepostgrado',
            name='tipo_descuento',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'monto fijo'), (1, 'porcentual')], null=True),
        ),
    ]
