# Generated by Django 3.1.2 on 2021-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0017_auto_20210416_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulantepostgrado',
            old_name='monto_descuento',
            new_name='monto_descuento_arancel',
        ),
        migrations.RenameField(
            model_name='postulantepostgrado',
            old_name='tipo_descuento',
            new_name='tipo_descuento_arancel',
        ),
        migrations.AddField(
            model_name='postulantepostgrado',
            name='monto_descuento_matricula',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postulantepostgrado',
            name='tipo_descuento_matricula',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'monto fijo'), (1, 'porcentual')], null=True),
        ),
        migrations.AlterField(
            model_name='periodoprocesomatricula',
            name='publico',
            field=models.PositiveSmallIntegerField(choices=[(0, 'primer año'), (1, 'curso superior'), (2, 'educación continua')]),
        ),
    ]
