# Generated by Django 3.1.2 on 2021-05-04 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0019_auto_20210430_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arancelestudiante',
            old_name='descripcion_beneficio',
            new_name='descripcion_beneficios',
        ),
    ]
