# Generated by Django 3.1.2 on 2021-05-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0004_carrera_tipo_carrera'),
        ('persona', '0010_auto_20210504_0012'),
        ('matricula', '0021_periodoprocesomatricula_planes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostulantePostgrado',
            new_name='PostulanteEducacionContinua',
        ),
        migrations.AlterModelTable(
            name='postulanteeducacioncontinua',
            table='postulante_educacion_continua',
        ),
    ]
