# Generated by Django 3.1.2 on 2021-05-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0005_plan_link_decreto'),
        ('pagos', '0014_auto_20210414_1751'),
        ('matricula', '0022_auto_20210504_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorarancel',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagos.productos'),
        ),
        migrations.AddField(
            model_name='valormatricula',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='academica.plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valormatricula',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagos.productos'),
        ),
        migrations.AlterField(
            model_name='valormatricula',
            name='proceso_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula'),
        ),
        migrations.AlterUniqueTogether(
            name='valormatricula',
            unique_together={('proceso_matricula', 'plan')},
        ),
    ]
