# Generated by Django 3.1.2 on 2021-05-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0023_auto_20210507_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoprocesomatricula',
            name='dcto_oportuno',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
