# Generated by Django 3.1.2 on 2021-05-13 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0024_periodoprocesomatricula_dcto_oportuno'),
    ]

    operations = [
        migrations.AddField(
            model_name='arancelestudiante',
            name='periodo_matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='matricula.periodoprocesomatricula'),
        ),
        migrations.AddField(
            model_name='matriculaestudiante',
            name='periodo_matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='matricula.periodoprocesomatricula'),
        ),
        migrations.AddField(
            model_name='periodoprocesomatricula',
            name='fecha_entrega_pagare',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodoprocesomatricula',
            name='fecha_pago_arancel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodoprocesomatricula',
            name='fecha_pago_matricula',
            field=models.DateField(blank=True, null=True),
        ),
    ]
