# Generated by Django 3.1.2 on 2021-06-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0005_plan_link_decreto'),
        ('matricula', '0025_auto_20210513_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoprocesomatricula',
            name='planes',
            field=models.ManyToManyField(blank=True, to='academica.Plan'),
        ),
    ]
