# Generated by Django 3.1.2 on 2021-06-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0026_auto_20210608_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulanteregular',
            name='modulo_ciencias',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='postulanteregular',
            name='percentil_lenguaje_matematica',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='postulanteregular',
            name='promedio_NEM',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='postulanteregular',
            name='promedio_lenguaje_matematica',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='postulanteregular',
            name='puntaje_NEM',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='postulanteregular',
            name='puntaje_ciencias',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='postulanteregular',
            name='puntaje_historia',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='postulanteregular',
            name='puntaje_lenguaje',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='postulanteregular',
            name='puntaje_matematica',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='postulanteregular',
            name='puntaje_ponderado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='postulanteregular',
            name='puntaje_ranking',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
