# Generated by Django 3.1.2 on 2021-06-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0027_auto_20210608_1746'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postulanteespecial',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postulanteespecial',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='postulanteespecial',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='postulanteespecial',
            name='proceso_matricula',
        ),
        migrations.RemoveField(
            model_name='postulanteespecial',
            name='subcriterio_ingreso',
        ),
        migrations.AlterUniqueTogether(
            name='postulanteregular',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postulanteregular',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='postulanteregular',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='postulanteregular',
            name='proceso_matricula',
        ),
        migrations.RemoveField(
            model_name='postulanteregular',
            name='via_ingreso',
        ),
        migrations.RemoveField(
            model_name='subcriterioadmisionespecial',
            name='criterio',
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='modulo_ciencias',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='percentil_lenguaje_matematica',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='promedio_NEM',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='promedio_lenguaje_matematica',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='puntaje_NEM',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='puntaje_ciencias',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='puntaje_historia',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='puntaje_lenguaje',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='puntaje_matematica',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='puntaje_ponderado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='puntaje_ranking',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.DeleteModel(
            name='CriterioAdmisionEspecial',
        ),
        migrations.DeleteModel(
            name='PostulanteEspecial',
        ),
        migrations.DeleteModel(
            name='PostulanteRegular',
        ),
        migrations.DeleteModel(
            name='SubcriterioAdmisionEspecial',
        ),
    ]
