# Generated by Django 4.0 on 2021-12-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0028_auto_20210610_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantedefinitivo',
            name='PACE',
            field=models.BooleanField(default=False, help_text='define si es que el estudiante proviene de un programa PACE, independiente de su vía de ingreso'),
        ),
        migrations.AlterField(
            model_name='postulantedefinitivo',
            name='numero_demre',
            field=models.CharField(help_text='Este número se utiliza como la contraseña del estudiante para ingresar al portal de matrícula', max_length=50),
        ),
        migrations.AlterField(
            model_name='postulantedefinitivo',
            name='preseleccionado_gratuidad',
            field=models.BooleanField(default=False, help_text='Atención: marcar esta opción resultará en un costo de matrícula y arancel de $0 para el estudiante'),
        ),
    ]
