# Generated by Django 4.0 on 2022-01-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0014_persona_autoriza_uso_imagen'),
        ('matricula', '0029_alter_postulantedefinitivo_pace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantedefinitivo',
            name='estudiante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postulante', to='persona.estudiante'),
        ),
        migrations.AlterField(
            model_name='postulanteeducacioncontinua',
            name='estudiante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postulanteeducontinua', to='persona.estudiante'),
        ),
    ]
