# Generated by Django 4.0 on 2022-03-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0030_alter_postulantedefinitivo_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratuidadestudiante',
            name='tiene_gratuidad',
            field=models.BooleanField(default=False),
        ),
    ]
