# Generated by Django 4.1.3 on 2023-01-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0033_rename_puntaje_matematica_postulantedefinitivo_puntaje_matematica_m1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='percentil_50',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='percentil_60',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
