# Generated by Django 4.1.3 on 2023-01-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0034_postulantedefinitivo_percentil_50_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulantedefinitivo',
            old_name='puntaje_matimatica_m2',
            new_name='puntaje_matematica_m2',
        ),
        migrations.AddField(
            model_name='postulantedefinitivo',
            name='puntaje_matematica',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
