# Generated by Django 4.1.3 on 2023-01-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0035_rename_puntaje_matimatica_m2_postulantedefinitivo_puntaje_matematica_m2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantedefinitivo',
            name='promedio_NEM',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='postulantedefinitivo',
            name='puntaje_NEM',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='postulantedefinitivo',
            name='puntaje_ciencias',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='postulantedefinitivo',
            name='puntaje_historia',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='postulantedefinitivo',
            name='puntaje_lenguaje',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='postulantedefinitivo',
            name='puntaje_matematica_m1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='postulantedefinitivo',
            name='puntaje_matematica_m2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='postulantedefinitivo',
            name='puntaje_ranking',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
