# Generated by Django 4.1.3 on 2023-01-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0036_alter_postulantedefinitivo_promedio_nem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantedefinitivo',
            name='puntaje_ponderado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
