# Generated by Django 3.1.2 on 2021-02-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='codigo_demre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='codigo_demre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
