# Generated by Django 3.1.2 on 2021-02-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20210211_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_demre', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provincias', to='general.region')),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='Provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunas', to='general.provincia'),
        ),
    ]
