# Generated by Django 3.1.2 on 2021-02-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20210216_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='Provincia',
            new_name='provincia',
        ),
        migrations.AlterField(
            model_name='comuna',
            name='codigo_demre',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigo_demre',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='codigo_demre',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
