# Generated by Django 3.1.2 on 2021-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20210216_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='codigo_demre',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigo_demre',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='codigo_demre',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
