# Generated by Django 3.1.2 on 2021-03-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20210218_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_demre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('codigo_mineduc', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.AlterField(
            model_name='comuna',
            name='codigo_demre',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigo_demre',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='codigo_demre',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
