# Generated by Django 3.1.2 on 2021-02-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20210205_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='direccion_numero',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
