# Generated by Django 3.1.2 on 2021-02-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20210226_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='emergencia_mail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'femenino'), (1, 'masculino'), (2, 'no especifica')], default=2),
        ),
    ]
