# Generated by Django 3.1.2 on 2021-03-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20210312_1608'),
        ('persona', '0006_auto_20210310_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudad_origen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion_coyhaique',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.pais'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'mujer'), (1, 'hombre'), (2, 'no especifica')], default=2),
        ),
    ]
