# Generated by Django 3.1.2 on 2021-03-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_auto_20210312_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='mail_institucional',
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
