# Generated by Django 3.1.2 on 2021-06-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20210609_1232'),
        ('persona', '0010_auto_20210504_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='periodo_ingreso_uaysen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='curso.periodo'),
        ),
    ]
