# Generated by Django 3.2.5 on 2021-10-29 13:55

from django.db import migrations, models
import django.db.models.deletion


estados_estudiantes = [
    {
        "pk": 1,
        "nombre": "Postergado",
        "id_SAI": 49,
        "id_ucampus": 12
    },
    {
        "pk": 2,
        "nombre": "Abandono",
        "id_SAI": 43,
        "id_ucampus": 4
    },
    {
        "pk": 3,
        "nombre": "Eliminado",
        "id_SAI": 41,
        "id_ucampus": 1
    },
    {
        "pk": 4,
        "nombre": "Regular",
        "id_SAI": 42,
        "id_ucampus": 3
    },
    {
        "pk": 6,
        "nombre": "Matrícula pendiente",
        "id_SAI": None,
        "id_ucampus": None
    },
    {
        "pk": 7,
        "nombre": "Matrícula anulada por cambio de carrera",
        "id_SAI": None,
        "id_ucampus": None
    },
    {
        "pk": 8,
        "nombre": "Matrícula anulada por retracto",
        "id_SAI": None,
        "id_ucampus": None
    },
    {
        "pk": 9,
        "nombre": "Matrícula anulada por otro motivo",
        "id_SAI": None,
        "id_ucampus": None
    },
    {
        "pk": 10,
        "nombre": "No Activo",
        "id_SAI": 40,
        "id_ucampus": 0
    },
    {
        "pk": 11,
        "nombre": "Retiro voluntario",
        "id_SAI": 51,
        "id_ucampus": 1001
    },
    {
        "pk": 12,
        "id_SAI": 44,
        "nombre": "Egresado",
        "id_ucampus": 5
    },
    {
        "pk": 13,
        "id_SAI": 50,
        "nombre": "Egresado",
        "id_ucampus": 13
    },
    {
        "pk": 14,
        "nombre": "En Proceso de Graduación",
        "id_SAI": 48,
        "id_ucampus": 11
    },
    {
        "pk": 15,
        "nombre": "Graduado",
        "id_SAI": 46,
        "id_ucampus": 8
    },
    {
        "pk": 16,
        "nombre": "En Proceso de Titulación",
        "id_SAI": 47,
        "id_ucampus": 10
    },
    {
        "pk": 17,
        "nombre": "Titulado",
        "id_SAI": 45,
        "id_ucampus": 7
    },
    {
        "pk": 18,
        "nombre": "En Causal de Eliminación",
        "id_SAI": 52,
        "id_ucampus": 15
    }
]


def crear_estados_estudiantes(apps, schema_editor):
    EstadoEstudiante = apps.get_model('persona', 'EstadoEstudiante')
    for estado in estados_estudiantes:
        EstadoEstudiante.objects.create(**estado)
    return


def migrar_estados_estudiantes(apps, schema_editor):
    Estudiante = apps.get_model('persona', 'Estudiante')
    EstadoEstudiante = apps.get_model('persona', 'EstadoEstudiante')

    estados = {
        0: 4,  # regular
        1: 1,  # congelado
        2: 2,  # abandono
        3: 3,  # eliminado
        6: 6,  # matrícula pendiente
        7: 7,  # matrícula anulada por cambio de carrera
        8: 8,  # matrícula anulada por retracto
        9: 9,  # matrícula anulada por otro motivo
        10: 10,  # No Activo
        11: 11,  # retiro voluntario
    }

    for estudiante in Estudiante.objects.all():
        estudiante.estado_estudiante = EstadoEstudiante.objects.get(pk=estados[estudiante.estado])
        estudiante.save()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0011_estudiante_periodo_ingreso_uaysen'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('id_ucampus', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id_SAI', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_estudiante',
            },
        ),

        # crear estados
        migrations.RunPython(crear_estados_estudiantes, migrations.RunPython.noop),

        migrations.AddField(
            model_name='estudiante',
            name='estado_estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='persona.estadoestudiante'),
            preserve_default=False,
        ),

        # migrar estados anteriores
        migrations.RunPython(migrar_estados_estudiantes, migrations.RunPython.noop),
    ]
