# Generated by Django 3.2.5 on 2021-11-04 18:24

from django.db import migrations, models
import django.db.models.deletion


def migrar_historial_estados_estudiantes(apps, schema_editor):
    Estudiante = apps.get_model('persona', 'Estudiante')
    HistorialEstadoEstudiante = apps.get_model('persona', 'HistorialEstadoEstudiante')

    for estudiante in Estudiante.objects.all():
        HistorialEstadoEstudiante.objects.create(
            estudiante=estudiante,
            estado_estudiante=estudiante.estado_estudiante,
            periodo=estudiante.periodo_ingreso,
        )
    return


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_auto_20211021_1203'),
        ('persona', '0012_auto_20211029_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='persona.estadoestudiante')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_estados', to='persona.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='curso.periodo')),
            ],
            options={
                'db_table': 'historial_estado_estudiante',
            },
        ),

        # rellenar historial con estado actual
        migrations.RunPython(migrar_historial_estados_estudiantes, migrations.RunPython.noop),
    ]
