# Generated by Django 4.0 on 2022-01-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0013_historialestadoestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='autoriza_uso_imagen',
            field=models.BooleanField(default=False),
        ),
    ]
