# Generated by Django 4.0 on 2022-03-02 19:08

from django.db import migrations


estados_estudiantes = [
    {
        'pk': 19,
        'nombre': 'Transferencia Interna',
        'id_SAI': None,
        'id_ucampus': None
    },
]


def crear_estados_estudiantes(apps, schema_editor):
    EstadoEstudiante = apps.get_model('persona', 'EstadoEstudiante')
    for estado in estados_estudiantes:
        EstadoEstudiante.objects.create(**estado)
    return


def eliminar_estados_estudiantes(apps, schema_editor):
    EstadoEstudiante = apps.get_model('persona', 'EstadoEstudiante')
    for estado in estados_estudiantes:
        EstadoEstudiante.objects.get(pk=estado['pk']).delete()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0014_persona_autoriza_uso_imagen'),
    ]

    operations = [
        migrations.RunPython(crear_estados_estudiantes, eliminar_estados_estudiantes),

        # elimina campo obsoleto
        migrations.RemoveField(
            model_name='estudiante',
            name='estado',
        ),
    ]
