# Generated by Django 4.0.3 on 2022-09-08 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0017_auto_20220419_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estudiante_antiguo',
            field=models.ForeignKey(blank=True, help_text='usado para mantener historial académico en cambios de carrera', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes_antiguos', to='persona.estudiante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='digito_verificador',
            field=models.CharField(blank=True, help_text='solo se usa para cedula de identidad', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mail_institucional',
            field=models.EmailField(blank=True, help_text='usado para login con google auth', max_length=200, null=True, unique=True),
        ),
    ]
