# Generated by Django 4.1.3 on 2022-12-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0018_alter_estudiante_estudiante_antiguo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='acepta_contrato',
            field=models.BooleanField(default=False),
        ),
    ]
