# Generated by Django 4.1.3 on 2023-01-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0021_alter_persona_archivo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
