# Generated by Django 3.1.6 on 2021-02-17 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0002_auto_20210205_1742'),
        ('general', '0003_auto_20210211_1621'),
        ('matricula', '0002_auto_20210211_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalidadCuotaPagare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('cantidad_cuotas', models.PositiveSmallIntegerField()),
                ('interes_mensual_mora', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
                ('codigo_decreto', models.CharField(max_length=50)),
                ('curso_asociado', models.PositiveSmallIntegerField(choices=[(0, 'primer año'), (1, 'cursos superiores')])),
                ('proceso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.procesomatricula')),
            ],
            options={
                'db_table': 'modalidad_cuota_pagare',
            },
        ),
        migrations.CreateModel(
            name='Pagare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('rut_estudiante', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('numero_cuotas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('monto_total_extras', models.PositiveIntegerField()),
                ('carnet_estudiante', models.FileField(upload_to='pagares/carnet/')),
                ('doc_enviado', models.FileField(upload_to='pagares/enviado/')),
                ('doc_provisorio', models.FileField(upload_to='pagares/provisorio/')),
                ('doc_recibido', models.FileField(upload_to='pagares/recibido/')),
                ('validado', models.BooleanField(default=False)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'enviado'), (1, 'validado'), (2, 'pago finalizado'), (3, 'anulado por gratuidad'), (4, 'anulado por cambio de carrera'), (5, 'anulado por repactación de deuda'), (6, 'anulado por retracto'), (7, 'anulado (otro motivo)')])),
                ('arancel_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.arancelestudiante')),
                ('modalidad_cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagare.modalidadcuotapagare')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
            options={
                'db_table': 'pagare',
            },
        ),
        migrations.CreateModel(
            name='TipoExtraPagare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_extra_pagare',
            },
        ),
        migrations.CreateModel(
            name='PagoExtraPagare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('monto', models.PositiveIntegerField()),
                ('justificacion', models.CharField(max_length=200)),
                ('pagare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagare.pagare')),
                ('tipo_extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagare.tipoextrapagare')),
            ],
            options={
                'db_table': 'pago_extra_pagare',
            },
        ),
        migrations.CreateModel(
            name='PagarePersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo_persona', models.PositiveSmallIntegerField(choices=[(0, 'aval'), (1, 'tutor legal')])),
                ('rut', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('carnet', models.FileField(upload_to='pagares/aval/')),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.comuna')),
                ('pagare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagare.pagare')),
            ],
            options={
                'db_table': 'pagare_persona',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoPagare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado_anterior', models.PositiveSmallIntegerField(choices=[(0, 'enviado'), (1, 'validado'), (2, 'pago finalizado'), (3, 'anulado por gratuidad'), (4, 'anulado por cambio de carrera'), (5, 'anulado por repactación de deuda'), (6, 'anulado por retracto'), (7, 'anulado (otro motivo)')])),
                ('estado_actual', models.PositiveIntegerField(choices=[(0, 'enviado'), (1, 'validado'), (2, 'pago finalizado'), (3, 'anulado por gratuidad'), (4, 'anulado por cambio de carrera'), (5, 'anulado por repactación de deuda'), (6, 'anulado por retracto'), (7, 'anulado (otro motivo)')])),
                ('autor_cambio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
                ('pagare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagare.pagare')),
            ],
            options={
                'db_table': 'historial_estado_pagare',
            },
        ),
        migrations.CreateModel(
            name='FechaCuotaPagare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('numero_cuota', models.PositiveSmallIntegerField()),
                ('fecha_pago', models.DateField()),
                ('modalidad_cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagare.modalidadcuotapagare')),
            ],
            options={
                'db_table': 'fecha_cuota_pagare',
            },
        ),
        migrations.CreateModel(
            name='CuotaPagare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('numero_cuota', models.PositiveSmallIntegerField()),
                ('monto_a_pagar', models.PositiveIntegerField()),
                ('fecha_cuota', models.DateField(blank=True, null=True)),
                ('monto_pagado', models.PositiveIntegerField()),
                ('fecha_pago', models.DateField()),
                ('orden_compra', models.IntegerField()),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'expirada'), (2, 'pagada'), (3, 'anulada')])),
                ('fecha_cuota_pagare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagare.fechacuotapagare')),
                ('pagare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagare.pagare')),
            ],
            options={
                'db_table': 'cuota_pagare',
            },
        ),
    ]
