# Generated by Django 3.1.2 on 2021-02-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0010_auto_20210226_1724'),
        ('pagare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagare',
            name='carnet_estudiante',
        ),
        migrations.RemoveField(
            model_name='pagare',
            name='doc_enviado',
        ),
        migrations.RemoveField(
            model_name='pagare',
            name='doc_provisorio',
        ),
        migrations.RemoveField(
            model_name='pagare',
            name='doc_recibido',
        ),
        migrations.AddField(
            model_name='pagare',
            name='monto_arancel',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagare',
            name='validado_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialestadopagare',
            name='estado_actual',
            field=models.PositiveIntegerField(choices=[(0, 'enviado'), (1, 'validado - pago pendiente'), (2, 'pago finalizado'), (3, 'anulado por gratuidad'), (4, 'anulado por cambio de carrera'), (5, 'anulado por repactación de deuda'), (6, 'anulado por retracto'), (7, 'anulado (otro motivo)'), (8, 'cancelado por cambio de forma de pago')]),
        ),
        migrations.AlterField(
            model_name='historialestadopagare',
            name='estado_anterior',
            field=models.PositiveSmallIntegerField(choices=[(0, 'enviado'), (1, 'validado - pago pendiente'), (2, 'pago finalizado'), (3, 'anulado por gratuidad'), (4, 'anulado por cambio de carrera'), (5, 'anulado por repactación de deuda'), (6, 'anulado por retracto'), (7, 'anulado (otro motivo)'), (8, 'cancelado por cambio de forma de pago')]),
        ),
        migrations.AlterField(
            model_name='modalidadcuotapagare',
            name='codigo_decreto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='modalidadcuotapagare',
            name='curso_asociado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'primer año'), (1, 'cursos superiores'), (2, 'todos')]),
        ),
        migrations.AlterField(
            model_name='modalidadcuotapagare',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='arancel_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagares', to='matricula.arancelestudiante'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'enviado'), (1, 'validado - pago pendiente'), (2, 'pago finalizado'), (3, 'anulado por gratuidad'), (4, 'anulado por cambio de carrera'), (5, 'anulado por repactación de deuda'), (6, 'anulado por retracto'), (7, 'anulado (otro motivo)'), (8, 'cancelado por cambio de forma de pago')], default=0),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='monto_total_extras',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
