# Generated by Django 3.1.2 on 2021-02-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagare', '0002_auto_20210226_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestadopagare',
            name='estado_actual',
            field=models.PositiveIntegerField(choices=[(0, 'esperando recepción'), (1, 'recibido - pago pendiente'), (2, 'pago finalizado'), (3, 'anulado por gratuidad'), (4, 'anulado por cambio de carrera'), (5, 'anulado por repactación de deuda'), (6, 'anulado por retracto'), (7, 'anulado (otro motivo)'), (8, 'cancelado por cambio de forma de pago')]),
        ),
        migrations.AlterField(
            model_name='historialestadopagare',
            name='estado_anterior',
            field=models.PositiveSmallIntegerField(choices=[(0, 'esperando recepción'), (1, 'recibido - pago pendiente'), (2, 'pago finalizado'), (3, 'anulado por gratuidad'), (4, 'anulado por cambio de carrera'), (5, 'anulado por repactación de deuda'), (6, 'anulado por retracto'), (7, 'anulado (otro motivo)'), (8, 'cancelado por cambio de forma de pago')]),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'esperando recepción'), (1, 'recibido - pago pendiente'), (2, 'pago finalizado'), (3, 'anulado por gratuidad'), (4, 'anulado por cambio de carrera'), (5, 'anulado por repactación de deuda'), (6, 'anulado por retracto'), (7, 'anulado (otro motivo)'), (8, 'cancelado por cambio de forma de pago')], default=0),
        ),
    ]
