# Generated by Django 3.1.2 on 2021-05-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0023_auto_20210507_1232'),
        ('academica', '0005_plan_link_decreto'),
        ('pagare', '0003_auto_20210226_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modalidadcuotapagare',
            old_name='codigo_decreto',
            new_name='decreto',
        ),
        migrations.AddField(
            model_name='modalidadcuotapagare',
            name='decreto_ano',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modalidadcuotapagare',
            name='fecha_entrega',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='modalidadcuotapagare',
            name='fecha_primera_cuota',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='modalidadcuotapagare',
            name='link_pagare',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='modalidadcuotapagare',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='academica.plan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modalidadcuotapagare',
            name='curso_asociado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'primer año'), (1, 'cursos superiores')]),
        ),
        migrations.AlterField(
            model_name='modalidadcuotapagare',
            name='interes_mensual_mora',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='modalidadcuotapagare',
            unique_together={('proceso_matricula', 'plan', 'cantidad_cuotas')},
        ),
    ]
