# Generated by Django 3.1.2 on 2021-05-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0005_plan_link_decreto'),
        ('matricula', '0023_auto_20210507_1232'),
        ('pagare', '0004_auto_20210507_1406'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modalidadcuotapagare',
            unique_together={('proceso_matricula', 'plan', 'cantidad_cuotas', 'curso_asociado')},
        ),
    ]
