# Generated by Django 3.1.2 on 2021-05-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagare', '0005_auto_20210507_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidadcuotapagare',
            name='fecha_entrega',
        ),
    ]
