# Generated by Django 4.0 on 2022-01-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagare', '0006_remove_modalidadcuotapagare_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagare',
            name='documento_escaneado',
            field=models.FileField(null=True, upload_to='pagares/'),
        ),
    ]
