# Generated by Django 4.0.3 on 2022-09-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagare', '0008_alter_pagare_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotapagare',
            name='fecha_cuota',
            field=models.DateField(blank=True, help_text='para poder agregar cuotas manualmente, sin una modalidad cuota definida', null=True),
        ),
        migrations.AlterField(
            model_name='modalidadcuotapagare',
            name='curso_asociado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'primer año'), (1, 'cursos superiores')], help_text='permite definir pagarés diferenciados para estudiantes nuevos y antiguos'),
        ),
        migrations.AlterField(
            model_name='modalidadcuotapagare',
            name='fecha_primera_cuota',
            field=models.CharField(blank=True, help_text='utilizado solo para informar al estudiante', max_length=50),
        ),
        migrations.AlterField(
            model_name='modalidadcuotapagare',
            name='link_pagare',
            field=models.CharField(blank=True, help_text='\nID del documento en google drive para generar el link de descarga del pagaré.<br>\nPara obtenerlo se debe abrir el documento en una ventana nueva y en la url se encuentra el id.<br>\ne.g: en <a>https://drive.google.com/file/d/1scpjrjnHdwgjc8Ya-oSQyYjLMyh4BgQv/view</a>\nel id es <b>1scpjrjnHdwgjc8Ya-oSQyYjLMyh4BgQv</b>.\n        ', max_length=200),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='monto_total_extras',
            field=models.PositiveIntegerField(default=0, help_text='para poder agregar valores extras, como matrícula o deudas anteriores'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='numero_cuotas',
            field=models.PositiveSmallIntegerField(blank=True, help_text='pensado para permitir crear pagarés sin una modalidad de cuota definida', null=True),
        ),
    ]
