# Generated by Django 3.1.2 on 2020-12-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('curso', '0002_auto_20201211_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoInscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'regular'), (1, 'modifica'), (2, 'elimina')])),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.periodo')),
            ],
            options={
                'db_table': 'proceso_inscripcion',
                'unique_together': {('nombre', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='EnvioInscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now=True)),
                ('felicidad', models.SmallIntegerField(default=0)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscripcion.procesoinscripcion')),
            ],
            options={
                'db_table': 'envio_inscripcion',
                'unique_together': {('persona', 'proceso')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.PositiveSmallIntegerField()),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'agregar'), (1, 'eliminar'), (2, 'permutar')])),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'aceptado'), (2, 'rechazado por cupo'), (3, 'rechazado por choque horario'), (4, 'rechazado por límite de créditos'), (5, 'curso ya inscrito para este semestre')], default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='curso.curso')),
                ('curso2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='curso.curso')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='inscripcion.envioinscripcion')),
            ],
            options={
                'db_table': 'solicitud_curso',
                'unique_together': {('envio', 'prioridad')},
            },
        ),
    ]
