# Generated by Django 3.2.5 on 2021-07-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitudcurso',
            unique_together={('envio', 'prioridad', 'tipo')},
        ),
    ]
