# Generated by Django 4.0.3 on 2022-10-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0018_alter_estudiante_estudiante_antiguo_and_more'),
        ('inscripcion', '0002_alter_solicitudcurso_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoInscripcionExcepcional',
            fields=[
                ('procesoinscripcion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inscripcion.procesoinscripcion')),
                ('estudiantes', models.ManyToManyField(to='persona.estudiante')),
            ],
            bases=('inscripcion.procesoinscripcion',),
        ),
    ]
