# Generated by Django 4.0.3 on 2022-10-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0018_alter_estudiante_estudiante_antiguo_and_more'),
        ('inscripcion', '0003_procesoinscripcionexcepcional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesoinscripcionexcepcional',
            name='estudiantes',
        ),
        migrations.AddField(
            model_name='procesoinscripcion',
            name='estudiante',
            field=models.ManyToManyField(blank=True, to='persona.estudiante'),
        ),
    ]
