# Generated by Django 4.0.3 on 2022-10-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_remove_procesoinscripcionexcepcional_estudiantes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcesoInscripcionExcepcional',
        ),
    ]
