# Generated by Django 4.0.6 on 2022-11-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0005_delete_procesoinscripcionexcepcional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcurso',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'aceptado'), (2, 'rechazado por cupo'), (3, 'rechazado por choque horario'), (4, 'rechazado por límite de créditos'), (5, 'curso ya inscrito para este semestre'), (6, 'pendiente aprobacion jefe de carrera')], default=0),
        ),
    ]
