# Generated by Django 3.1.2 on 2020-12-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField(auto_now_add=True)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'acta',
            },
        ),
        migrations.CreateModel(
            name='AyudanteCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ayudante_curso',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seccion', models.PositiveSmallIntegerField(default=1)),
                ('cupo', models.PositiveSmallIntegerField()),
                ('estado_curso', models.PositiveSmallIntegerField(choices=[(0, 'registrado'), (1, 'en progreso'), (2, 'terminado')], default=0)),
            ],
            options={
                'db_table': 'curso',
                'ordering': ['periodo', 'ramo'],
            },
        ),
        migrations.CreateModel(
            name='DocenteCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.PositiveSmallIntegerField(choices=[(0, 'profesor responsable'), (1, 'profesor cátedra'), (2, 'profesor práctica')], default=0)),
            ],
            options={
                'db_table': 'docente_curso',
            },
        ),
        migrations.CreateModel(
            name='EstudianteCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_finalizacion', models.PositiveSmallIntegerField(choices=[(0, 'en-progreso'), (1, 'aprobado'), (2, 'reprobado'), (3, 'eliminado'), (4, 'postergado')], default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='curso.curso')),
            ],
            options={
                'db_table': 'estudiante_curso',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.curso')),
            ],
            options={
                'db_table': 'evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
            ],
            options={
                'db_table': 'modulo',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, 'primer semestre'), (2, 'segundo semestre')])),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'periodo',
                'ordering': ('ano', 'numero'),
                'unique_together': {('ano', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estudiante_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.estudiantecurso')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.evaluacion')),
            ],
            options={
                'db_table': 'nota',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(1, 'lunes'), (2, 'martes'), (3, 'miércoles'), (4, 'jueves'), (5, 'viernes'), (6, 'sábado')])),
                ('tipo_horario', models.PositiveSmallIntegerField(choices=[(0, 'catedra'), (1, 'ayudantía'), (2, 'laboratorio'), (3, 'paso práctica'), (4, 'otro')], default=0)),
                ('sala', models.CharField(blank=True, max_length=200)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='curso.curso')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.modulo')),
            ],
            options={
                'db_table': 'horario',
                'ordering': ['curso'],
            },
        ),
    ]
