# Generated by Django 3.1.2 on 2020-12-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('academica', '0001_initial'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantecurso',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.estudiante'),
        ),
        migrations.AddField(
            model_name='docentecurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='curso.curso'),
        ),
        migrations.AddField(
            model_name='docentecurso',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona'),
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.periodo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='ramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.ramo'),
        ),
        migrations.AddField(
            model_name='ayudantecurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayudantes', to='curso.curso'),
        ),
        migrations.AddField(
            model_name='ayudantecurso',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona'),
        ),
        migrations.AddField(
            model_name='acta',
            name='estudiante_curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acta', to='curso.estudiantecurso'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('evaluacion', 'estudiante_curso')},
        ),
        migrations.AlterUniqueTogether(
            name='estudiantecurso',
            unique_together={('curso', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='docentecurso',
            unique_together={('curso', 'persona')},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('ramo', 'periodo', 'seccion')},
        ),
        migrations.AlterUniqueTogether(
            name='ayudantecurso',
            unique_together={('curso', 'persona')},
        ),
    ]
