# Generated by Django 3.2.5 on 2021-08-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20210609_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='id_SAI',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='id_ucampus',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='id_SAI',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='id_ucampus',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
