# Generated by Django 3.2.5 on 2021-08-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_auto_20210817_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
