# Generated by Django 3.2.5 on 2021-10-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_auto_20210818_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEstudianteCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, unique=True)),
                ('completado', models.BooleanField()),
                ('aprobado', models.BooleanField()),
                ('id_ucampus', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id_SAI', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_estudiante_curso',
            },
        ),
        migrations.RemoveField(
            model_name='estudiantecurso',
            name='estado_finalizacion',
        ),
        migrations.AddField(
            model_name='estudiantecurso',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='estudiantecurso',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='curso.estadoestudiantecurso'),
            preserve_default=False,
        ),
    ]
