# Generated by Django 4.0 on 2022-03-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0015_agregar_estado_trans_interna'),
        ('curso', '0006_auto_20211021_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantecurso',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='persona.estudiante'),
        ),
    ]
