# Generated by Django 4.0.2 on 2022-03-25 18:55

from django.db import migrations

from curso.models import EstadoEstudianteCurso

estados_estudiante_curso = [
    {
        "nombre": "Eliminado por Postergación",
        "completado": True,
        "aprobado": False,
        "id_SAI": None,
        "id_ucampus": None
    },
    {
        "nombre": "Eliminado",
        "completado": True,
        "aprobado": False,
        "id_SAI": None,
        "id_ucampus": None
    }]


def crear_estados_estudiante_curso(apps, schema_editor):
    for estado in estados_estudiante_curso:
        EstadoEstudianteCurso.objects.update_or_create(nombre=estado['nombre'], defaults=estado)


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_alter_estudiantecurso_estudiante'),
    ]

    operations = [migrations.RunPython(crear_estados_estudiante_curso)]
