# Generated by Django 4.0 on 2022-06-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0008_auto_20220325_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentecurso',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(0, 'profesor responsable'), (1, 'profesor cátedra'), (2, 'profesor práctica'), (3, 'profesor colaborador')], default=0),
        ),
        migrations.AlterField(
            model_name='horario',
            name='tipo_horario',
            field=models.PositiveSmallIntegerField(choices=[(0, 'catedra'), (1, 'ayudantía'), (2, 'laboratorio'), (3, 'taller'), (4, 'práctica'), (5, 'otro')], default=0),
        ),
    ]
