# Generated by Django 4.0.3 on 2022-09-08 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0013_alter_mallaelectiva_semestre_and_more'),
        ('curso', '0009_alter_docentecurso_rol_alter_horario_tipo_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='creditos',
            field=models.PositiveSmallIntegerField(blank=True, help_text='se guarda automáticamente en caso de que cambien los créditos de un ramo', null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estado_curso',
            field=models.PositiveSmallIntegerField(choices=[(0, 'registrado'), (1, 'en progreso'), (2, 'terminado')], default=0, help_text='permite determinar si un curso sigue en progreso después del final del semestre'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='activo',
            field=models.BooleanField(help_text='\n            influye en la lógica del sistema, define qué ramos se están cursando actualmente, los\n            procesos de inscripción académica a los que se puede acceder, entre otros.\n        '),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='link_decreto',
            field=models.CharField(blank=True, help_text='solo para guardar registro', max_length=300),
        ),
        migrations.CreateModel(
            name='SeccionCursoPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.plan')),
            ],
        ),
    ]
