# Generated by Django 4.0.3 on 2022-09-08 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0010_alter_curso_creditos_alter_curso_estado_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccioncursoplan',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='curso.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccioncursoplan',
            name='seccion',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='seccioncursoplan',
            table='seccioncursoplan',
        ),
    ]
