# Generated by Django 4.0.3 on 2022-09-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0013_alter_mallaelectiva_semestre_and_more'),
        ('curso', '0011_seccioncursoplan_curso_seccioncursoplan_seccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccioncursoplan',
            name='ramo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='academica.ramo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='seccioncursoplan',
            unique_together={('ramo', 'seccion', 'plan')},
        ),
        migrations.RemoveField(
            model_name='seccioncursoplan',
            name='curso',
        ),
    ]
