# Generated by Django 4.0.3 on 2022-09-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0013_alter_mallaelectiva_semestre_and_more'),
        ('curso', '0012_seccioncursoplan_ramo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeccionCursoPlan',
            new_name='CursosCompartidos',
        ),
        migrations.AlterModelTable(
            name='cursoscompartidos',
            table='cursos_compartidos',
        ),
    ]
