# Generated by Django 4.0.3 on 2022-10-19 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0013_rename_seccioncursoplan_cursoscompartidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='examen_reprobatorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='nota_maxima_examen',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='curso',
            name='nota_minima_examen',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='curso',
            name='ponderacion_examen',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='curso',
            name='tiene_examen',
            field=models.BooleanField(default=True),
        ),
    ]
