# Generated by Django 4.0.3 on 2022-10-21 14:27

import curso.validadores
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0014_curso_examen_reprobatorio_curso_nota_maxima_examen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nota_maxima_examen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[curso.validadores.validatar_nota]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nota_minima_examen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[curso.validadores.validatar_nota]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ponderacion_examen',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='La ponderación de la evaluación debe ser entre 1 y 100'), django.core.validators.MaxValueValidator(100, message='La ponderación de la evaluación debe ser entre 1 y 100')]),
        ),
    ]
