# Generated by Django 4.0.3 on 2022-10-24 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0016_alter_curso_nota_maxima_examen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='ponderacion',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1, message='La ponderación de la evaluación debe ser entre 1 y 100'), django.core.validators.MaxValueValidator(100, message='La ponderación de la evaluación debe ser entre 1 y 100')]),
            preserve_default=False,
        ),
    ]
