# Generated by Django 4.0.3 on 2022-10-25 16:04

import curso.validadores
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0013_alter_mallaelectiva_semestre_and_more'),
        ('curso', '0017_evaluacion_ponderacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nota_maxima_examen',
            new_name='nota_eximicion_examen',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='curso',
        ),
        migrations.AddField(
            model_name='estudiantecurso',
            name='nota_examen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='estudiantecurso',
            name='nota_presentacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='estudiantecurso',
            name='nota_recuperativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.nota'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodo',
            name='fecha_limite_primera_evaluacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[curso.validadores.validatar_nota]),
        ),
        migrations.CreateModel(
            name='CategoriaActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academica.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponderacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='La ponderación de la evaluación debe ser entre 1 y 100'), django.core.validators.MaxValueValidator(100, message='La ponderación de la evaluación debe ser entre 1 y 100')])),
                ('categoria_actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.categoriaactividad')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='curso.actividad'),
            preserve_default=False,
        ),
    ]
