# Generated by Django 4.0.3 on 2022-10-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0013_alter_mallaelectiva_semestre_and_more'),
        ('curso', '0018_rename_nota_maxima_examen_curso_nota_eximicion_examen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaactividad',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academica.plan'),
        ),
        migrations.AlterField(
            model_name='estudiantecurso',
            name='nota_recuperativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.nota'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='evaluacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nota', to='curso.evaluacion'),
        ),
    ]
