# Generated by Django 4.0.3 on 2022-11-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0020_curso_nota_aprobacion_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='curso.curso'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='curso.actividad'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nota', to='curso.evaluacion'),
        ),
    ]
