# Generated by Django 4.0.3 on 2022-11-02 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0021_alter_actividad_curso_alter_evaluacion_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.actividad'),
        ),
    ]
