# Generated by Django 4.0.3 on 2022-11-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0022_alter_actividad_curso_alter_evaluacion_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='curso.curso'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='curso.actividad'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='curso.evaluacion'),
        ),
    ]
