# Generated by Django 4.0.3 on 2022-11-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0023_alter_actividad_curso_alter_evaluacion_actividad_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together={('curso', 'categoria_actividad')},
        ),
    ]
