# Generated by Django 4.1.3 on 2022-11-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0023_alter_actividad_curso_alter_evaluacion_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_examen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_recuperativa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='pendiente_ingreso',
            field=models.BooleanField(default=False),
        ),
    ]
