# Generated by Django 4.0.3 on 2022-11-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0024_curso_fecha_examen_curso_fecha_recuperativa_and_more'),
        ('curso', '0025_alter_curso_nota_aprobacion_curso'),
    ]

    operations = [
    ]
