# Generated by Django 4.0 on 2021-12-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0013_historialestadoestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'causa_solicitud',
            },
        ),
        migrations.CreateModel(
            name='EstadoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'regular'), (1, 'congelado'), (2, 'abandono'), (3, 'eliminado'), (4, 'suspendido'), (5, 'completado'), (6, 'matrícula pendiente'), (7, 'matrícula anulada por cambio de carrera'), (8, 'matrícula anulada por retracto'), (9, 'matrícula anulada por otro motivo'), (10, 'No Activo'), (11, 'retiro voluntario'), (12, 'no regular')], default=0)),
            ],
            options={
                'db_table': 'estado_estudiante_test',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('periodo', models.CharField(max_length=6)),
                ('justificacion_estudiante', models.TextField()),
                ('estado', models.CharField(choices=[(0, 'Pendiente'), (1, 'Aprobada'), (2, 'Rechazada'), (3, 'No Procede'), (4, 'Expirada')], max_length=50)),
                ('resolucion', models.CharField(max_length=16)),
                ('comentario_revisor', models.TextField()),
                ('causa_principal', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='solicitudes.causasolicitud')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.estudiante')),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('instrucciones', models.CharField(max_length=500)),
                ('plazo_resolucion', models.CharField(max_length=60)),
                ('estados_validos', models.ManyToManyField(to='solicitudes.EstadoEstudiante')),
            ],
            options={
                'db_table': 'tipo_solicitud',
            },
        ),
        migrations.CreateModel(
            name='SolicitudReintegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='solicitudes.solicitud')),
            ],
            options={
                'db_table': 'solicitud_reintegracion',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPostergacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_semestres', models.IntegerField(choices=[(1, '1'), (2, '2')])),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='solicitudes.solicitud')),
            ],
            options={
                'db_table': 'solicitud_postergacion',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCambioCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=50)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='solicitudes.solicitud')),
            ],
            options={
                'db_table': 'solicitud_cambio_carrera',
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitudes.tiposolicitud'),
        ),
    ]
