# Generated by Django 4.0 on 2021-12-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_auto_20211021_1203'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.periodo'),
        ),
        migrations.AlterField(
            model_name='tiposolicitud',
            name='plazo_resolucion',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
