# Generated by Django 4.0 on 2021-12-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0013_historialestadoestudiante'),
        ('solicitudes', '0002_alter_solicitud_periodo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoEstudiante',
        ),
        migrations.AlterField(
            model_name='tiposolicitud',
            name='estados_validos',
            field=models.ManyToManyField(to='persona.EstadoEstudiante'),
        ),
    ]
