# Generated by Django 4.0 on 2021-12-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='comentario_revisor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='resolucion',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
