# Generated by Django 4.0 on 2022-01-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0011_alter_mallaelectiva_conjunto_ramos_and_more'),
        ('solicitudes', '0005_alter_solicitud_comentario_revisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobada'), (2, 'Rechazada'), (3, 'No Procede'), (4, 'Expirada')], default=0),
        ),
        migrations.AlterField(
            model_name='solicitudcambiocarrera',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academica.carrera'),
        ),
    ]
