# Generated by Django 4.0 on 2022-01-17 16:20

from django.db import migrations

tipos_solicitudes = [
    {
        "nombre":"Postergación",
        "pk":1,
        "instrucciones":"Instrucciones para postergar: texto",
        "estados_validos": 4
    },
    {
        "nombre":"Cambio Carrera",
        "pk":2,
        "instrucciones":"Instrucciones para cambiarse de carrera: texto",
        "estados_validos": 4
    },
    {
        "nombre":"Reincorporación",
        "pk":3,
        "instrucciones":"Instrucciones para reincorporarse: texto",
        "estados_validos": 1
    },
    {
        "nombre":"Renuncia",
        "pk":4,
        "instrucciones":"Instrucciones para renunciar a la carrera: texto",
        "estados_validos": 4
    }]

def crear_tipos_solicitud(apps, schema_editor):
    TipoSolicitud = apps.get_model('solicitudes', 'TipoSolicitud')
    for tipo in tipos_solicitudes:
        estados = tipo.pop('estados_validos')
        var = TipoSolicitud.objects.create(**tipo)
        var.estados_validos.add(estados)
    return


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_alter_solicitud_estado_and_more'),
    ]

    operations = [migrations.RunPython(crear_tipos_solicitud)
    ]


