# Generated by Django 4.0.2 on 2022-03-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_auto_20220117_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='solicitudes.solicitud')),
            ],
            options={
                'db_table': 'solicitud_renuncia',
            },
        ),
    ]
