# Generated by Django 4.0.3 on 2022-04-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_solicitudrenuncia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobada'), (2, 'Rechazada'), (3, 'No Procede'), (4, 'Expirada'), (5, 'Renuncia Pendiente')], default=0),
        ),
        migrations.CreateModel(
            name='PeriodoTipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitudes.tiposolicitud')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
