# Generated by Django 4.0 on 2022-04-21 21:11

from django.db import migrations


def agregar_estado_valido(apps, schema_editor):
    TipoSolicitud = apps.get_model('solicitudes', 'TipoSolicitud')
    renuncia = TipoSolicitud.objects.get(nombre="Renuncia")
    renuncia.estados_validos.add(1)  # postergado
    return


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_alter_solicitud_estado_periodotiposolicitud'),
    ]

    operations = [
        migrations.RunPython(agregar_estado_valido)
    ]
