# Generated by Django 4.0.3 on 2022-05-30 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_alter_tiposolicitud_plazo_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposolicitud',
            name='plazo_resolucion',
            field=models.DurationField(default=datetime.timedelta(days=84), null=True),
        ),
    ]
