# Generated by Django 4.0.3 on 2022-05-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_alter_tiposolicitud_plazo_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='comentario_revisor',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='resolucion',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
    ]
