# Generated by Django 4.0.3 on 2022-05-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_alter_solicitud_comentario_revisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='justificacion_revisor',
            field=models.TextField(blank=True),
        ),
    ]
