# Generated by Django 4.0.4 on 2022-06-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_solicitud_justificacion_revisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='valida_causas',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
