# Generated by Django 4.0.4 on 2022-06-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0016_solicitud_causas_revisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='causa_principal',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='causas_estudiante',
            field=models.ManyToManyField(related_name='causas_estudiante', to='solicitudes.causasolicitud'),
        ),
    ]
