# Generated by Django 4.0.4 on 2022-06-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0017_remove_solicitud_causa_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='valida_causas',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
