# Generated by Django 4.0 on 2022-07-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0018_alter_solicitud_valida_causas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='causas_estudiante',
            field=models.ManyToManyField(related_name='causas_estudiante', to='solicitudes.CausaSolicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='causas_revisor',
            field=models.ManyToManyField(blank=True, related_name='causas_revisor', to='solicitudes.CausaSolicitud'),
        ),
    ]
